name: Jekyll FTP deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out main
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Install Jekyll
      uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      run: |
        gem install bundler jekyll
        bundle install
    - name: Test site
      run: bundle exec rake test
    - name: Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      env:
        FTP_SERVER: ${{secrets.FTP_SERVER}}
        FTP_USERNAME: ${{secrets.FTP_USERNAME}}
        FTP_PASSWORD: ${{secrets.FTP_PASSWORD}}
        LOCAL_DIR: _site
        git-ftp-args: --dry-run
