name: Jekyll to FTP CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out main
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Install Jekyll
      run: |
        sudo gem install bundler jekyll
        sudo bundle install
    - name: Test site
      run: bundle exec rake test
    - name: Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      env:
        FTP_SERVER: ${{secrets.FTP_SERVER}}
        FTP_USERNAME: ${{secrets.FTP_USERNAME}}
        FTP_PASSWORD: ${{secrets.FTP_PASSWORD}}
        LOCAL_DIR: _site
        git-ftp-args: --dry-run
